version: "2"
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - IGNORE_TLS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_TTL=300
      - PDF_CONVERTER_URL=html-pdf-converter:8001
    links:
      - redis
      - html-pdf-converter
    ports:
      - "8080:8080"
    volumes:
      - "/app/public"
  redis:
    image: redis

  nginx-proxy:
    image: quay.io/ukhomeofficedigital/nginx-proxy:v1.5.1
    environment:
      - PROXY_SERVICE_HOST=app
      - PROXY_SERVICE_PORT=8080
      - NAXSI_USE_DEFAULT_RULES=FALSE
      - ADD_NGINX_SERVER_CFG=add_header Cache-Control private;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;location /public {add_header Cache-Control max-age=86400;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;alias /app/public;}
      - ERROR_REDIRECT_CODES=599
    ports:
      - "443:443"
      - "80:80"
    links:
      - app
    volumes_from:
      - app
      
  html-pdf-converter:
    image: quay.io/ukhomeofficedigital/html-pdf-converter:01442cbca45c8c1965a64f680d8fab95998e5238
    environment:
      - CHROME_HOST=chrome
    ports:
      - "8001:8001"
    links:
      - chrome

  chrome:
    image: quay.io/ukhomeofficedigital/docker-chrome-headless:v1.0.0
