---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    downscaler/uptime: Mon-Fri 08:00-18:00 Europe/London
  name: {{ .NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        name: {{ .NAME }}
        app: {{ .NAME }}
        service: hof-form-example
    spec:
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_URL }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis
           - name: BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: refugee-integration-loans
                      key: name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: refugee-integration-loans
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: refugee-integration-loans
                  key: secret_access_key
            - name: KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: refugee-integration-loans
                  key: kms_key_id

