---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-vault
spec:
  {{if eq .KUBE_NAMESPACE "cto-prod"}}
  replicas: 3
  {{end}}
  {{if eq .KUBE_NAMESPACE "cto-preprod"}}
  replicas: 3
  {{end}}
  {{if eq .KUBE_NAMESPACE "cto-dev"}}
  replicas: 1
  {{end}}
  selector:
    matchLabels:
      app: file-vault
  template:
    metadata:
      labels:
        name: file-vault
        service: file-vault
    spec:
      containers:
        - name: file-vault
          image: quay.io/ukhomeofficedigital/file-vault:2936ce44e4ca1ad90b3b0526b9abf73c46000de2
          imagePullPolicy: Always
          resources:
            limits:
              {{if eq .KUBE_NAMESPACE "cto-prod"}}
              memory: "1024Mi"
              {{end}}
              {{if eq .KUBE_NAMESPACE "cto-preprod"}}
              memory: "256Mi"
              {{end}}
              {{if eq .KUBE_NAMESPACE "cto-dev"}}
              memory: "256Mi"
              {{end}}
              cpu: 200m
          env:
            # because the internal virus scanner has a self signed cert!
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: FILE_VAULT_URL
            {{if eq .KUBE_NAMESPACE "cto-dev"}}
              value: https://file-vault-dev.cto-notprod.homeoffice.gov.uk
            {{end}}
            {{if eq .KUBE_NAMESPACE "cto-preprod"}}
              value: https://file-vault-dev.cto-preprod.homeoffice.gov.uk
            {{end}}
            {{if eq .KUBE_NAMESPACE "cto-prod"}}
              value: https://file-vault-dev.cto-prod.homeoffice.gov.uk
            {{end}}
            - name: PORT
              value: "3000"
            - name: CLAMAV_REST_URL
              value: https://clamav.virus-scan.svc.cluster.local/scan
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: secret_access_key
            - name: AWS_KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: kms_key_id
            - name: AWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-password
                  key: password
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: aws-region
            - name: AWS_SIGNATURE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: aws-signature-version
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: bucket_name
            - name: AWS_EXPIRY_TIME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: aws-expiry-time
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: node-env
          securityContext:
            runAsNonRoot: true

        - name: keycloak-proxy
          image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.2.2
          resources:
            limits:
              memory: "256Mi"
              cpu: 200m
          env:
            - name: PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: secret
            - name: PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: id
            - name: PROXY_DISCOVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: keycloak-realm
            - name: PROXY_LISTEN
              value: 127.0.0.1:3001
            - name: PROXY_REDIRECTION_URL
            {{if eq .KUBE_NAMESPACE "cto-dev"}}
              value: https://file-vault-dev.cto-notprod.homeoffice.gov.uk
            {{end}}
            {{if eq .KUBE_NAMESPACE "cto-preprod"}}
              value: https://file-vault-dev.cto-preprod.homeoffice.gov.uk
            {{end}}
            {{if eq .KUBE_NAMESPACE "cto-prod"}}
              value: https://file-vault-dev.cto-prod.homeoffice.gov.uk
            {{end}}
            - name: PROXY_UPSTREAM_URL
              value: "http://127.0.0.1:3000"
            - name: PROXY_REVOCATION_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: keycloak-realm-revocation-url
          command:
            - "/opt/keycloak-proxy"
            - "--resources=uri=/file|methods=GET,POST|roles=caseworkers"
            - "--resources=uri=/*"
            - "--enable-logging=true"
            - "--enable-json-logging=true"
          securityContext:
            runAsNonRoot: true

        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3
          resources:
            limits:
              memory: "256Mi"
              cpu: 200m
          env:
            - name: PROXY_SERVICE_HOST
              value: 127.0.0.1
            - name: PROXY_SERVICE_PORT
              value: "3001"
            - name: ENABLE_UUID_PARAM
              value: "FALSE"
            - name: HTTPS_REDIRECT
              value: "FALSE"
            - name: NAXSI_USE_DEFAULT_RULES
              value: "FALSE"
            - name: PORT_IN_HOST_HEADER
              value: "FALSE"
            - name: ERROR_REDIRECT_CODES
              value: "599"
            - name: CLIENT_MAX_BODY_SIZE
              value: "200"

          ports:
            - containerPort: 10080
            - containerPort: 10443
          volumeMounts:
            - mountPath: /public
              name: public
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: public
          emptyDir: {}
